# See if we add the plugins : jekyll-sitemap and jekyll-seo-tag (check: https://jekyllrb.com/docs/step-by-step/10-deployment/)
# See if we compress css output

title: "BlogFish"
url: ""

feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

paginate: 5

permalink: 404.html

plugins:
  - jekyll-target-blank

collections:
  category:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
    values:
      layout: "main"
  - scope:
      path: "feed.xml"
    values:
      layout: "simple"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: /p/:title
      layout: "post"
  
